# Generated by Django 4.0.1 on 2022-02-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcl',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
    ]
